trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Default # Change to a Microsoft-hosted agent for testing
    steps:
    - script: ls -la $(Build.SourcesDirectory)  # List contents to verify Dockerfile
      displayName: 'List source directory contents'
      
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)
